### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by hilltty** [DasSharkk/AdvancedInvisibleItemframes#10]
If you specify a custom number of items for crafting in the config, then when you try to break the frame, the number that is specified will drop out, and not just one

**Comment by DasSharkk** [comment]
True, didn't think about it. I'll fix it really quick

**Comment by DasSharkk** [comment]
https://github.com/DasSharkk/AdvancedInvisibleItemframes/releases/tag/release-1.3
Thanks for your contribution to this project aswell <3

**Comment by DasSharkk** [comment]
I just updated the release again, because there were missing dependencies, the new jar should work
