### ISSUE TITLE
Number of crafted items

### ISSUE THREAD

**Issue by hilltty** [DasSharkk/AdvancedInvisibleItemframes#7]
Hey, is it possible to add the ability to change the number of frames created at a time? It would be very helpful

**Comment by DasSharkk** [comment]
Currently not, but I'll add it to my todo

**Comment by DasSharkk** [comment]
@hilltty Added in the newest release aswell! You can download it here: https://github.com/DasSharkk/AdvancedInvisibleItemframes/releases/tag/release-1.2
