### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by hilltty** [DasSharkk/AdvancedInvisibleItemframes#8]
If you try to break an invisible frame, the usual one will drop out.

**Comment by DasSharkk** [comment]
Yep, I know this one, but I need to do a little workaround to fix this. I'll do it in the next few days

**Comment by DasSharkk** [comment]
@hilltty Fixed in the newest release! You can download it here: https://github.com/DasSharkk/AdvancedInvisibleItemframes/releases/tag/release-1.2
